version: '3.1'

services:
  control:
    build: './python_control'
    working_dir: /usr/src/app
    command: python runSimulation.py --url="http://emulator:5000" --dayOfYear=152 --dayOffset=0 --simDuration=172800 --fmuStep=600