version: '3.1'

services:
  emulator:
    build: './emulator'
    container_name: building_emulator
    working_dir: /home/developer
    # logging:
            # driver: none 
    command: python startREST.py --fmuPath=/home/developer/models/wrapped.fmu --fmuStep=60