version: '3.1'

services:
  control:
    build: './python_control'
    container_name: python
    working_dir: /usr/src/app
    command: python client_examples.py --url="http://emulator:5000" --dayOfYear=152 --dayOffset=0 --simDuration=1200 --fmuStep=600